### ISSUE TITLE
<div> element in wysihtml5 editor during paste operation

### ISSUE THREAD

**Issue by ajayaks** [perfectsense/brightspot-cms#187]
In CMS wysihtml5 editor we have one scenario like on copy & paste the data on editor so during this operations its adding <div> element for everyone break like below.
Checked the code its behaving as per implementation.

Means if we copy & paste next below three lines:-
SomeText1

SomeText2

It would be converted into below:-

<div>SomeText1</div>

<div><br></div>

<div>SomeText2</div>

As per current logic its fine but when we are simply writing multi line text its fine means we having <br> element and no <div> around. 

So wondering can we have same functionality on paste operation also means no <div> element , it should behave same like when we write multi line text.

Please suggest.

**Comment by rhino88** [comment]
We've since updated our Rich Text Editor to handle more common copy/paste scenarios. I will close this issue for now, but let us know if you encounter the issue with the Rich Text Editor in the [latest release of Brightspot CMS](https://github.com/perfectsense/brightspot-cms/releases/tag/v3.2.6800-ed293d).
