### ISSUE TITLE
Items returned by Site.itemsPredicate()

### ISSUE THREAD

**Issue by KodakAlarisUser** [perfectsense/brightspot-cms#295]
The documentation on the Brightspot site (http://www.brightspot.com/docs/3.0/brightspot-tools/multisite-customization) seems to recommend using the itemsPredicate() function when querying for content in a specific Site.  We have found that the predicate causes Global content to be returned in addition to content owned by the specific Site in question.  Is that expected behavior?

**Comment by Ryan-Anderson** [comment]
This is intentional. The current implementation is meant to allow you to filter out objects not accessible by your current site. 

If you look at the implementation [here](https://github.com/perfectsense/brightspot-cms/blob/master/db/src/main/java/com/psddev/cms/db/Site.java#L220), you can see that Global items are explicitly included.

**Comment by Ryan-Anderson** [comment]
Closing this issue for now. Let us know if you have any additional questions!
