### ISSUE TITLE
Creating RSS Feeds

### ISSUE THREAD

**Issue by drochester** [perfectsense/brightspot-cms#525]
Hi there,

I'm with Penske Media Corporation. We recently acquired Indiewire. I need to create RSS and MRSS feeds for new partners. I could really use instruction on how to do so. Thus far, I've been unsuccessful in locating any documentation.

**Comment by hyoolim** [comment]
Hi, I believe Ben is handling your account. Can you direct all support questions through him?

**Comment by drochester** [comment]
Ben does currently handle support questions for IndieWire. Ben is very busy at the moment. All that I'm looking for is documentation on how to create an RSS feed? Can I not obtain those instructions from you?

**Comment by hyoolim** [comment]
The reason why I was directing you to Ben is because creating RSS or MRSS feeds is a general question about Java web development, not about Brightspot.

One of the more popular libraries for creating those feeds in Java is ROME (https://github.com/rometools/rome), and here's a rough usage of it:

```java
SyndFeed feed = new SyndFeedImpl();
List<SyndEntry> entries = new ArrayList<>();

for (Article article : Query.from(Article.class).iterable(0)) {
    SyndEntry entry = new SyndEntryImpl();
    entry.setTitle(article.getHeadline());
    entries.add(entry);
}

try (Writer writer = new FileWriter("feed.xml")) {
    SyndFeedOutput output = new SyndFeedOutput();
    ouput.output(feed, writer);
}
```

As you can see, the documentation and instruction is more about how to use ROME and output that as a page from a Java web container. Brightspot isn't involved (other than to query the data, which IS documented at http://www.brightspot.com/docs/3.1/query-api/clauses).
