### ISSUE TITLE
Stack trace on Admin page

### ISSUE THREAD

**Issue by wiverson** [perfectsense/brightspot-cms#61]
Environment:

```
Icarus:~ wiverson$ mvn -version
Apache Maven 3.2.5 (12a6b3acb947671f09b81f49094c53f426d8cea1; 2014-12-14T09:29:23-08:00)
Maven home: /Users/wiverson/devenv/apache-maven-3.2.5
Java version: 1.8.0_31, vendor: Oracle Corporation
Java home: /Library/Java/JavaVirtualMachines/jdk1.8.0_31.jdk/Contents/Home/jre
Default locale: en_US, platform encoding: UTF-8
OS name: "mac os x", version: "10.10.2", arch: "x86_64", family: "mac"
```

Repro steps:
- Default quick start install
- Apply patch at [https://github.com/perfectsense/brightspot-cms/commit/8ee11de158beae4ebf20429ba3ce288bcf79a326]
- Log in as admin/admin
- Click to view Profile in upper-right corner

Profile window generates following error:

```
Can't render /cms/WEB-INF/field/locale.jsp!

Unable to compile class for JSP: 

An error occurred at line: 57 in the jsp file: /cms/WEB-INF/field/locale.jsp
The type new Comparator<Locale>(){} must implement the inherited abstract method Comparator<Locale>.thenComparing(Function<? super Locale,? extends U>, Comparator<? super U>)
54: 
55:         List<Locale> availableLocales = Arrays.<Locale>asList(Locale.getAvailableLocales());
56: 
57:         Collections.<Locale>sort(availableLocales, new Comparator<Locale>() {
58:             @Override
59:             public int compare(Locale o1, Locale o2) {
60:                 String dn1 = o1.getDisplayName(o1);
```

Error appears in user interface, but didn't see anything in the default log.

**Comment by lteague** [comment]
This is a strange bug we don't typically see except when using the maven cargo plugin with tomcat 7 and java 8, and only on brightspot/dari 2.4. The bug is in ECJ, and has to do with using Java 8 to compile with -target 1.6.

There are two possible fixes. One, use java 7 when using cargo, or two, update your pom.xml to use Tomcat 8 (thereby preventing the JSP compiler from using java 6) like so:

                <version>1.4.12</version>
                <configuration>
                    <container>
                        <containerId>tomcat8x</containerId>
                        <zipUrlInstaller>
                            <url>http://archive.apache.org/dist/tomcat/tomcat-8/v8.0.18/bin/apache-tomcat-8.0.18.zip</url>
                            <downloadDir>${user.home}/.dari/cargo-downloads</downloadDir>
                        </zipUrlInstaller>
                    </container> ...

We're committed to supporting Java 1.6 on 2.4, so we can't force either of these changes on our end, but using one or the other of these should get you and and running.

**Comment by wiverson** [comment]
Looks good now.  Thanks!
