### ISSUE TITLE
Dynamic URL/routes to pages not modelled from a content type

### ISSUE THREAD

**Issue by nickdunn** [perfectsense/brightspot-cms#73]
Similar to #70, regarding controller logic and routing.

I have a Hospital content type, to which Consultants are related. A hospital has a URL /my-hospital and I want to list consultants at /my-hospital/consultants. This listing does not need any bespoke managed content, all dynamic.

In something like Rails or Backbone I would have a route such as:

    /:hospital_name/consultants

Where I can then map this pattern onto a controller to render the template that lists consultants for the given hospital.

Does Brightspot support dynamic routing such as this, so that CMS-generated URLs directly associated to a model can have child pages auto-generated?

**Comment by richfdrums** [comment]
Hi Nick,

One option is a special "**" syntax you can use in your CMS permalinks for a given model class. This allows you to then have any number of sub/child paths that you could look for and handle in your template (layout) renderer.

E.g.,  The Hospital class could have createPermalink() return a "/my-hospital/**" value.  Your layout renderer could contain logic that parses the URL and handles /my-hospital/  vs. /my-hospital/consultants accordingly.

Hope that helps,
~Rich

**Comment by nickdunn** [comment]
Thanks Rich, will investigate if that would work here. Are there alternative options?

**Comment by hyoolim** [comment]
Nick, note that for your specific example, you don't really need separate custom controller or routing logic if you use the `**` syntax. Here's a barebones example:

`Hospital.java`:

    @Renderer.Paths({
        @Renderer.Path(value = "hospital.jsp"),
        @Renderer.Path(context = "fallback", value = "hospital-fallback.jsp"),
        @Renderer.Path(context = "consultants", value = "hospital-consultants.jsp")
    })
    public class Hospital extends Content {

        public String findContext(HttpServletRequest request) {
            switch (request.getPathInfo()) {
                case "/consultants" :
                    return "consultants";
                default :
                    return "fallback";
            }
        }

        public List<Consultant> findConsultants() {
            return Query.from(Consultant.class).where("hospital = ?", this).selectAll();
        }
    }

`hospital.jsp`:

    <cms:render context="${content.findContext(pageContext.request)}" value="${content}" />

`hospital-consultants.jsp`:

    <c:forEach var="consultant" items="${content.findConsultants()}"> ... </c:forEach>

The reason why we structure things this way is because we typically find that it's difficult to follow routing logic when it's far removed from the model/view, so we tend to have more controller logic in our model than what you might see in some of the other libraries.

Having said all that, if you really want to introduce a router or more formal MVC framework, we'd recommend adding Spring or something similar that has much more comprehensive APIs than we could support. Since our default routing is done via a servlet filter that runs last, it's pretty easy to add a filter where you can add custom routing logic before the CMS processes anything.
