### ISSUE TITLE
Question: add new icons to WYSIWYG editor

### ISSUE THREAD

**Issue by nickdunn** [perfectsense/brightspot-cms#76]
I'm sure I've seen reference to this before but cannot find in the documentation. We would like to:

* add heading support to the Rich Text editor (H2–6)
* remove ability to align left/centre/right

Where is this configured?

Example screenshot:

![](http://cdn.brightspotcms.psdops.com/dims4/default/b9f5f5d/2147483647/resize/700x/quality/90/?url=http%3A%2F%2Fd3qqon7jsl4v2v.cloudfront.net%2Fc0%2F63%2Fd85215f040a3bdc6c9540c3375ca%2Fscreenshot-2015-02-04-172404png.24.04.png)

**Comment by kphenix** [comment]
Nick,

The ability to add custom CSS can be found in Admin > Settings > RTE

You can see some examples here in the [Rich Text Editor](http://www.brightspot.com/docs/2.4/publishing-guide/publishing#rich-text-editor) docs.

Here's an actual example and the snippet:

![custom css](https://cloud.githubusercontent.com/assets/1231990/6467265/1b53f1ac-c19b-11e4-9020-4afa53d1fb38.png)

```
font-size:24px;
color:#000000;
```

**Comment by nickdunn** [comment]
Fantastic, thanks. Hadn't spotted this.

As a follow up question: I'm finding that the editor is adding `<br>` instead of `<p>` for line breaks. This is unexpected (Chrome/OSX). Is this a known bug or something badly configured?

**Comment by hyoolim** [comment]
That's expected. We do this to preserve what the user is entering so that the developer has the option of applying custom conversion, which sometimes requires them to distinguish between 1 and 2 line breaks. For the most common case of converting 2 line breaks into `<p>` tags, you can use `ReferentialText#toPublishables` API. This is also called for you automatically if you use the `<cms:render>` tag.
